### ISSUE TITLE
Problem with the loging: "The CSRF tokens do not match."

### ISSUE THREAD

**Issue by tschomacker** [Formulae-Litterae-Chartae/formulae-capitains-nemo#1056]
Entering the proper credentials in https://werkstatt.formulae.uni-hamburg.de/auth/login causes "The CSRF tokens do not match."-Error. So currently there is no possibility to log in. 

Check the following possible roots for the problem:
- [x] Lack of a valid SSL-certificate
- [x] Cookies or browser settings
- [x] Not enough disk space 

TODOS:
- [x] fix the problem or add a more descriptive error message (that references this issue)

**Comment by sonofmun** [comment]
The CSRF token shouldn't have anything to do with the SSL-certificate. It should be based on the SECRET_KEY environment variable and the algorithm that Flask-WTF uses to produce the key. Take a look at the Grinberg tutorial for a bit more background, if you need it: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iii-web-forms

**Comment by tschomacker** [comment]
Thanks for the unexpected support info!

**Comment by tschomacker** [comment]
**Solution**: The issue seems to be resolved after getting more disk space. 

Neither cookies nor the SSL certificate seemed to be cause. In theory it is possible to [customize the error response](https://flask-wtf.readthedocs.io/en/1.2.x/csrf/#customize-the-error-response). Since, the error is not occurring any more I cannot really implement or test the error handler. If the error re-occurs in the future - please re-open this issue
